version: "3"
services:
  db:
    image: mysql:5.6
    container_name: ghoul-api.db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --character-set-client=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-client-handshake=OFF
      - --innodb-large-prefix=ON
      - --innodb-file-per-table=ON
      - --innodb-file-format=Barracuda
      - --innodb-file-format-max=Barracuda
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ghoul
      MYSQL_USER: ghoul
      MYSQL_PASSWORD: ghoul123
      TZ: UTC
    volumes:
      - db-data:/var/lib/mysql

  # EnablePostgreSQL: remove the db service above, uncomment the following
  # db:
  #   image: postgres:9.6
  #   container_name: ghoul-api.db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: ghoul
  #     POSTGRES_USER: ghoul
  #     POSTGRES_PASSWORD: ghoul123
  #   volumes:
  #     - db-data:/var/lib/postgresql/data

volumes:
  db-data:
